name: Build and Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

defaults:
  run:
    shell: bash

env:
  CUDA_ARCH: -arch=all-major

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: slime_calculator-linux-amd64
            arch: amd64
          #- os: ubuntu-24.04-arm
          #  artifact_name: slime_calculator-linux-arm64
          #  arch: arm64
          - os: windows-latest
            artifact_name: slime_calculator-windows-amd64
            arch: amd64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup CUDA (x86_64)
        if: matrix.arch == 'amd64'
        uses: Jimver/cuda-toolkit@v0.2.35
        id: cuda-toolkit
        with:
          cuda: "13.2.0"

      - name: Verify CUDA
        if: matrix.arch == 'amd64'
        run: nvcc -V

      - name: Setup CUDA (Linux ARM64)
        if: matrix.os == 'ubuntu-24.04-arm'
        run: |
          sudo apt-get update
          sudo apt-get install -y nvidia-cuda-toolkit

      - name: Setup MSVC (Windows)
        if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build (Linux)
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-24.04-arm'
        run: ./build.sh

      - name: Build (Windows)
        if: matrix.os == 'windows-latest'
        shell: cmd
        run: |
          call build.bat

      - name: Package (Linux)
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-24.04-arm'
        run: |
          mv build/slime_cmp build/slime_calculator_linux_${{ matrix.arch }}_cmp
          mv build/slime_main build/slime_calculator_linux_${{ matrix.arch }}_main
          mv build/slime_circle build/slime_calculator_linux_${{ matrix.arch }}_circle
          zip ${{ matrix.artifact_name }}.zip build/*

      - name: Package (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          Compress-Archive -Path build/* -DestinationPath ${{ matrix.artifact_name }}.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
          generate_release_notes: true
